### ISSUE TITLE
关于红外接收的选型

### ISSUE THREAD

**Issue by KunBoy5240** [HalfSweet/AIR32_IRUniversalRemoteControls#1]
请问你的这个电路，红外接收采用的是一体化红外接收还是普通的红外接收管？那么如果我用的是一体化红外接收头还需不需要做误差处理也就是你的“IR_LOGIC_1_HIGH_LEVEL_TIME - IR_ERROR_TIME”

**Comment by HalfSweet** [comment]
使用的是一体的红外接收管，自动滤波38k的调制信号。
一般来说都需要加入一定的误差时间来避免误判断

**Comment by KunBoy5240** [comment]
我按照了你万能学习部分接收到了红外信号，发射时也是基于你的发射思路，可还是不能控制家电，请问问题是出在哪呢？
/
![Uploading QQ截图20230423170639.png…]()

**Comment by KunBoy5240** [comment]
![QQ截图20230423170639](https://user-images.githubusercontent.com/97332061/233830483-a6947a08-8d8d-4c05-83ae-25b4aae86704.png)

**Comment by HalfSweet** [comment]
你的硬件是什么样的？是否方便提供下原理图？

**Comment by KunBoy5240** [comment]
![QQ截图20230423171720](https://user-images.githubusercontent.com/97332061/233830958-00271df9-dad8-41ae-9eee-02e9b5b626d7.png)

**Comment by KunBoy5240** [comment]
还有我将接受到的红外信号打印出来看是符合格力空调的红外编码规则的包括时序等等，但是我再发出去用我这块开发板上的一体化接收头接收到的红外信息是有问题的毫无规律可言，我在想可能是不是发的没太大问题，但是接收的时候一边在发一边接收会影响到。实在不理解我的这个程序是错在了代码还是硬件电路出现了问题

**Comment by KunBoy5240** [comment]
这是我的捕获处理，看了和你的思路大体相似
![QQ截图20230423193605](https://user-images.githubusercontent.com/97332061/233837496-230b2807-303e-4f42-b18c-96b390faaaa9.png)
这是我在发射红外信号时的逻辑处理，继续开启了捕获通道来捕获自发送的红外信号，可是断点查看接收到的信号脉宽是有问题的
![QQ截图20230423193828](https://user-images.githubusercontent.com/97332061/233837571-570c139c-61cf-4e1d-91cd-ecf30816089a.png)

**Comment by KunBoy5240** [comment]
还有我想请问一下大佬，为什么我的这个红外发射出去自接收发现一共接收了139为高低电平的脉宽数据，可是前面有大概100位都是不太正确的，后面的几十位虽说有误差但还是对得上，请问一下这种情况问题是出在了哪呢？有偿求问

**Comment by HalfSweet** [comment]
你有逻辑分析仪吗？有的话建议加上之后看看时序能不能对上。
另外建议你发我邮件或者加我QQ联系，issue不太常看

**Comment by KunBoy5240** [comment]
请问一下qq

**Comment by HalfSweet** [comment]
2522182733
<halfsweet@halfsweet.cn>

**Comment by KunBoy5240** [comment]
qq没搜索到呢

**Comment by HalfSweet** [comment]
你再试试，我把隐私打开了
